### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by jpcapone** [oylsister/ZombieSharp#15]
Where exactly do you place the downloaded files within the CSGO folder structure?

**Comment by jpcapone** [comment]
I think i figured it out using the folder structure from the zip file.  Now it appears that it doesn't take effect.  When I do meta list I don't see it.  Any suggestions?

**Comment by oylsister** [comment]
this thing need counterstrikesharp with runtime.

**Comment by jpcapone** [comment]
i got that.  When I do meta list from the command line from the console i get
`> meta list
[Client]   [01] Movement Unlocker (1.0) by Vauff
[Client]   [02] CounterStrikeSharp (0.1.0) by Roflmuffin`

**Comment by oylsister** [comment]
obviously because this thing is not metamod plugin, you could find it in ``css_plugins list`` instead

**Comment by jpcapone** [comment]
When I type `css_plugins list` in the console i get `[CSS] You are missing the correct permissions [@css/generic] to execute this command.`  I am not sure how to rectify this but would appreciate any suggestions.

**Comment by Wideuz** [comment]
https://github.com/roflmuffin/CounterStrikeSharp i think you should go to here because it is counter strike sharp problem :)

**Comment by jpcapone** [comment]
> https://github.com/roflmuffin/CounterStrikeSharp i think you should go to here because it is counter strike sharp problem :)

I figured it out.  I was running the command from the console window of an attached client. 
`Command: css_plugins list`
```
Response:   List of all plugins currently loaded by CounterStrikeSharp: 1 plugins loaded.
  [#1:LOADED]: "Zombie Sharp" (1.1.2 Alpha) by Oylsister, Kurumi, Sparky
```
 Now that we know i have it running properly, what configuration steps would you recommend?  Like where do the .json files go?  How do I configure a match?

**Comment by Wideuz** [comment]
> > https://github.com/roflmuffin/CounterStrikeSharp i think you should go to here because it is counter strike sharp problem :)
> 
> I figured it out. I was running the command from the console window of an attached client. `Command: css_plugins list`
> 
> ```
> Response:   List of all plugins currently loaded by CounterStrikeSharp: 1 plugins loaded.
>   [#1:LOADED]: "Zombie Sharp" (1.1.2 Alpha) by Oylsister, Kurumi, Sparky
> ```
> 
> Now that we know i have it running properly, what configuration steps would you recommend? Like where do the .json files go? How do I configure a match?

check zombiesharp's readme file   i think there are some essential like weapon and some respawns and some zombie settings

**Comment by jpcapone** [comment]
Ok, my question is i am not seeing any zombies in game.  Please tell me how to do that and I will go away.

**Comment by oylsister** [comment]
The game mode starts after warmup is ended. There will be option to enable it during warmup in newer version.
