### ISSUE TITLE
 [HELP] Can you help with changing the model?

### ISSUE THREAD

**Issue by t4r1k58** [oylsister/ZombieSharp#19]
I'm sorry for my bad english. I checked the sources and zombie sharp is working properly on my server. I just couldn't adjust the zombie and human models. Any ideas on how to do it?

**Comment by oylsister** [comment]
currently it's not possible to do.

**Comment by oylsister** [comment]
Have to wait for someone finding out how to make it possible.

**Comment by oylsister** [comment]
Check the ReadME.md
