### ISSUE TITLE
Playerclass change command

### ISSUE THREAD

**Issue by xLeviNx** [oylsister/ZombieSharp#20]
Add ability to change player class. Currently cannot figure out how to change class for users after adding a few more classes. Also to implement the player class on next round

**Comment by oylsister** [comment]
the current beta build doesn't allow player to change class yet. I still can't decide yet if chat menu is the best option for class menu change.

**Comment by oylsister** [comment]
This is now in dev branch https://github.com/oylsister/ZombieSharp/commit/d19abe85124c8a70acc2afda7640957ebfcd4705

**Comment by oylsister** [comment]
done https://github.com/oylsister/ZombieSharp/pull/21
