### ISSUE TITLE
crash running plugin start

### ISSUE THREAD

**Issue by metacop** [oylsister/ZombieSharp#26]
I am on Linux(ubuntu) and I carry out all the installation steps, it lists the plugin in "css_plugin list" but when I enter the server, when I restart the game with bots, the server crashes. and I can't try even one round with zombie sharp mode. This happens when the warm-up round ends and the game is restarted and the server is deleted and shut down.

![image](https://github.com/oylsister/ZombieSharp/assets/56640826/ff5c9347-e46f-4e7f-b64e-34eb6b3d61c7)

![image](https://github.com/oylsister/ZombieSharp/assets/56640826/870ae11c-dbc1-4c94-b846-44086964e0b4)

(final console message, this is the last thing it shows when the server closes )
![image](https://github.com/oylsister/ZombieSharp/assets/56640826/e123a37f-308f-4905-9e64-21d00516775c)

![image](https://github.com/oylsister/ZombieSharp/assets/56640826/975c5435-77b4-4229-b530-1c01bf3872cd)
Load plugin

![image](https://github.com/oylsister/ZombieSharp/assets/56640826/746cca8b-8a82-4558-b546-381483e6e9c6)

i use: last version Stable version
144v counter strike sharp

**Comment by metacop** [comment]
> I am on Linux(ubuntu) and I carry out all the installation steps, it lists the plugin in "css_plugin list" but when I enter the server, when I restart the game with bots, the server crashes. and I can't try even one round with zombie sharp mode. This happens when the warm-up round ends and the game is restarted and the server is deleted and shut down.
> 
> ![image](https://private-user-images.githubusercontent.com/56640826/298309946-ff5c9347-e46f-4e7f-b64e-34eb6b3d61c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3OTI5ODYsIm5iZiI6MTcwNTc5MjY4NiwicGF0aCI6Ii81NjY0MDgyNi8yOTgzMDk5NDYtZmY1YzkzNDctZTQ2Zi00ZTdmLWI2NGUtMzRlYjZiM2Q2MWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIzMTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3YWJlOGRkM2FjODE5ZmVlY2UzMTJkNDA3ZjRhMDU3NWRlMDkzNTM5MGE3YjEyZTkxMDk3ZWU2ZmY5Y2ZkM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6KQiv2xfjVnI0XWbn7utrs2ra0yv2_Lwkj9yuiPI0KY)
> 
> ![image](https://private-user-images.githubusercontent.com/56640826/298309953-870ae11c-dbc1-4c94-b846-44086964e0b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3OTI5ODYsIm5iZiI6MTcwNTc5MjY4NiwicGF0aCI6Ii81NjY0MDgyNi8yOTgzMDk5NTMtODcwYWUxMWMtZGJjMS00Yzk0LWI4NDYtNDQwODY5NjRlMGI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIzMTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVkM2M1NDQ2NzA3NDliZWIwZTU0M2U1YWQ1MzkwYWM4OTIzMmM1NzU4ZTZmMTRiODVmNDNjNWQzNjc2N2U2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WTkS44q-Ty-Q4fvuuUIamoV5mlRpHjV8ZMLDtLZ_oHo)
> 
> (final console message, this is the last thing it shows when the server closes ) ![image](https://private-user-images.githubusercontent.com/56640826/298309957-e123a37f-308f-4905-9e64-21d00516775c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3OTI5ODYsIm5iZiI6MTcwNTc5MjY4NiwicGF0aCI6Ii81NjY0MDgyNi8yOTgzMDk5NTctZTEyM2EzN2YtMzA4Zi00OTA1LTllNjQtMjFkMDA1MTY3NzVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIzMTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYjlhNGEyYjM1MzAzYzRhMzRjNGFmZWQxZmE1MjI1MzcwNjYwZjFmNTVlYmJhZWUyZDA3NWMyZWI4ZTkzMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jjDcWp3pCccSIrSE7gjgx52mFtUrViL3SaQ_-z75tQU)
> 
> ![image](https://private-user-images.githubusercontent.com/56640826/298310000-975c5435-77b4-4229-b530-1c01bf3872cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3OTI5ODYsIm5iZiI6MTcwNTc5MjY4NiwicGF0aCI6Ii81NjY0MDgyNi8yOTgzMTAwMDAtOTc1YzU0MzUtNzdiNC00MjI5LWI1MzAtMWMwMWJmMzg3MmNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIzMTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjYzlkYjM2OGE4MGI2MDQyMzk0ZjkxNWIyYWI3ZjgwY2E4NTg1MDJmMTk4Mjk4MWFkODQ1NmRiNjY0M2VkYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PpIOfbQx8B6kzxY7V7KWcF3y17BLLsER1ALB-Fqel1g) Load plugin
> 
> ![image](https://private-user-images.githubusercontent.com/56640826/298310142-746cca8b-8a82-4558-b546-381483e6e9c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3OTI5ODYsIm5iZiI6MTcwNTc5MjY4NiwicGF0aCI6Ii81NjY0MDgyNi8yOTgzMTAxNDItNzQ2Y2NhOGItOGE4Mi00NTU4LWI1NDYtMzgxNDgzZTZlOWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDIzMTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyMGI2NzA1MWRmZmU4NDNiZjE3ZTc0MzhkMzAwNzY3MTA3YjgwOTRkOTczMjdjYTM0ODUxMTAxOTkyYWQyZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rcim9Kql_pSZ12zU7QWodHcrw-C4AlXbNMeUfN1RsMI)
> 
> i use: last version Stable version 144v counter strike sharp

update: The mode works now, my solution was to compile it from Linux. dotnet build

problem: but now I'm having trouble with player resources/models.

The route that I have, the models are in "
game/csgo/characters/models/camareman_ported_cs2.vmdl_c"

![image](https://github.com/oylsister/ZombieSharp/assets/56640826/b8d60b6e-199d-4b7c-b780-30a9c5ab016b)

![image](https://github.com/oylsister/ZombieSharp/assets/56640826/030970ec-b1aa-4d95-98b7-22b799bd93ab)

![image](https://github.com/oylsister/ZombieSharp/assets/56640826/3448434b-23c4-4141-b7bc-58a39e6735c3)

**Comment by metacop** [comment]
help me pls

![image](https://github.com/oylsister/ZombieSharp/assets/56640826/2b7da890-c20a-4e9c-9057-c328d8c92562)

**Comment by metacop** [comment]
> help me pls
> 
> ![image](https://private-user-images.githubusercontent.com/56640826/298315211-2b7da890-c20a-4e9c-9057-c328d8c92562.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MDE3OTEsIm5iZiI6MTcwNTgwMTQ5MSwicGF0aCI6Ii81NjY0MDgyNi8yOTgzMTUyMTEtMmI3ZGE4OTAtYzIwYS00ZTljLTkwNTctYzMyOGQ4YzkyNTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDAxNDQ1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0Y2VjNzJkNGY0M2I3ZWEzNGFmMzc2NGZhN2JiNTdmOTI3OWNhMDQxY2I5MTEwYWRmYmZhMzgyNzBhNGZhYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TYihEFzsoCOaanDeqDwK1z4nIs-rcESn85jVcIvMB2U)

updated: fix the name the file has vmdl_c but in the file it should be without _c. Now it doesn't give me any error on the console, but I still get an error in the game, that is, the 3D model "ERROR" does not show the player

**Comment by oylsister** [comment]
```json
{
    "Resources": [
	"characters\\models\\nozb1\\2b_nier_automata_player_model\\2b_nier_player_model.vmdl"
    ],
```

**Comment by oylsister** [comment]
where you placed the model in your game folder?

**Comment by metacop** [comment]
> where you placed the model in your game folder?

updated: 

change the model for humans, the original police model and it works for humans.

but in zombies it does not load the model/resource.

the folder/path is
game\csgo\characters\models\kolka\metro_cop\metro_cop.vmdl_c

![image](https://github.com/oylsister/ZombieSharp/assets/56640826/4dbc0b83-b3ce-4b47-92c5-70fbbbeee8cc)

my  resources
![image](https://github.com/oylsister/ZombieSharp/assets/56640826/48329708-3700-47a0-a412-3ab158bed53a)


playerclasses.json

![image](https://github.com/oylsister/ZombieSharp/assets/56640826/7f52ab37-030d-46d7-942b-f763fcbd0129)

folder model

![image](https://github.com/oylsister/ZombieSharp/assets/56640826/c9bca79c-c60c-4b2e-8a1b-f4b176d1cd22)

help me
I have tried 3 models, could you give me one that works or one that is working for you to test?

Everything seems to be fine. For the tests I am using another PC on my local network, entering through the IP where the server PC is. Maybe downloads are not enabled? downloads for clients? Is there a way to activate that? in server.cfg or something like that?

**Comment by oylsister** [comment]
There is no way client can downloads your custom model in cs2, since they have no fastdl. You have to make other player put your model to game folder manually.

**Comment by metacop** [comment]
> There is no way client can downloads your custom model in cs2, since they have no fastdl. You have to make other player put your model to game folder manually.

I was reading on github, that cs2 does not allow fastdl. but it does allow a workshop for personalized maps.
 https://help.dathost.net/article/144-cs2-custom-and-workshop-maps

but I don't understand, I've played on zombie scape servers with custom player zombies models. and it has downloaded, do you have an idea how that was done?

**Comment by oylsister** [comment]
I believe this is more like configuration issues than the code issue. Double check these list below
- Put a model in both game folder and server folder.
- use // in json config files and not / 
- put vmdl and not vmdl_c

if you're calling model in workshop file, check the model path in .vpk too
