### ISSUE TITLE
How to download custom models from server in CS2

### ISSUE THREAD

**Issue by ELDment** [oylsister/ZombieSharp#30]
**How to download custom models in CS2？**

**Comment by ELDment** [comment]
**If the client does not download the model files, <br>can the clients' player see the model after "Precache" executing on the server?**

**Comment by ELDment** [comment]
CS2 will not download my model files

**Comment by oylsister** [comment]
Precache and Downloading is different things. You have to force a player to download the model and put it in game folder manually.

**Comment by ELDment** [comment]
> Precache and Downloading is different things. You have to force a player to download the model and put it in game folder manually.

**What should be the absolute path of the ***characters*** folder**
 (what should be the parent directory of the ***characters*** folder)

**Comment by oylsister** [comment]
read the description for playerclasses config
