### ISSUE TITLE
Crash on new round start

### ISSUE THREAD

**Issue by oylsister** [oylsister/ZombieSharp#8]
This happened when the second round start (not after warmup round), could be the weapon removing issues.

**Comment by oylsister** [comment]
Fixed #9

**Comment by LianZiZhou** [comment]
My server also occasionally has this problem. I tried to find many possible points, but I couldn't completely solve the problem. Do you have any better suggestions? I would be very grateful if you could tell me.

**Comment by oylsister** [comment]
> My server also occasionally has this problem. I tried to find many possible points, but I couldn't completely solve the problem. Do you have any better suggestions? I would be very grateful if you could tell me.

First thing. The server log, CS# version, metamod version and your server os

**Comment by LianZiZhou** [comment]
> > My server also occasionally has this problem. I tried to find many possible points, but I couldn't completely solve the problem. Do you have any better suggestions? I would be very grateful if you could tell me.
> 
> First thing. The server log, CS# version, metamod version and your server os



> > My server also occasionally has this problem. I tried to find many possible points, but I couldn't completely solve the problem. Do you have any better suggestions? I would be very grateful if you could tell me.
> 
> First thing. The server log, CS# version, metamod version and your server os

Thank you for your reply. I use the latest metamod and css api. After applying the convar mentioned in issue #24, it has not crashed for 12 hours. Before, it would crash every 30 minutes.
There is no log to provide, the server just throws a segmentation fault at th start of a new round.

**Comment by LianZiZhou** [comment]
#24

**Comment by oylsister** [comment]
you still haven't told me about server os. Windows or linux?

**Comment by oylsister** [comment]
since there has been no reply I'm gonna closed it.
